### PR TITLE
Update vendored version of secp256k1-zkp

### PR DESCRIPTION
**Pull request by apoelstra**
Also bump major version of both secp256k1-zkp and secp256k1-zkp-sys.

Next step toward https://github.com/ElementsProject/rust-elements/issues/202#issuecomment-2199980614

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
I think this misses a change log entry, other than that ACK.

**Comment by apoelstra** [comment]
Added a commit with CHANGELOG entries.

**Review by jonasnick — APPROVED** [review]
ACK c1feb16e960058bc3771da2d186d90b4e8773766

**Comment by apoelstra** [comment]
Tagged, and published both crates.

**Pull request merged**
