### PR TITLE
Update secp256k1 dependency

### LINKED ISSUE #79: Update `secp256k1` to `0.29`
`bitcoin@0.32` uses `secp256k1@0.29`

### PR DESCRIPTION
**Pull request by apoelstra**
Also do some other deferred maintenance.

Fixes #79.

### CODE REVIEW

**Comment by bennyhodl** [comment]
Is this going to be merged and released soon?

**Review by jonasnick — APPROVED** [review]
ACK 4fb4de38f8e412a7acdaf10160b9f36cb3a5aa39

**Comment by apoelstra** [comment]
> Is this going to be merged and released soon?

I'd like to update the copy of libsecp256k1-zkp as well to fix https://github.com/ElementsProject/rust-elements/issues/202 and then yes, an update is a high priority.

@jonasnick do you know what the relationship between libsecp and libsecp-zkp is right now? Can I just update the libsecp-zkp in this library to `master` and expect things to work? I believe we depend here on the context objects from both libraries to be identical.

**Comment by jonasnick** [comment]
Yes I'd expect that updating libsecp-zkp in this library will work. Good point about the context object; it's identical in both forks of the library.

**Pull request merged**
